config/routes.rb
Rails.application.routes.draw do

  # Definierar rutter och root sätter start url.
  root 'pages#home'
  get 'about', to: 'pages#about'

  # Ny väg för att utföra crud på artiklar.
  resources :articles

  # Skapa users
  get 'signup', to: 'users#new'
  resources :users, expect: [:new]  
 
  # Inloggning på sidan
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Kategorier till artiklar, ska ej gå att ta bort.
  resources :categories, expect: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :article_categories #En artikel har många artikelkategorier.
    has_many :categories, through: :article_categories #En artikel har många kategorier genom artikelkategorier.

    # Validerar att en titel/beskrivning finns samt innehållslängd, innan en artikel lagras i db.
    validates_presence_of :title
    validates_length_of :title, minimum: 3, maximum: 50

    validates_presence_of :description
    validates_length_of :description, minimum: 10, maximum: 200
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    # Private metoden set_article exekveras innan de definierade funktioner nedan.
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    # Kräver en inloggade user förutom nedan definierade funktioner.
    before_action :require_user, except: [:index, :show]
    # Kräver en specifik user som publiserat artikeln för att ändra och ta bort.
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        # Delar upp sidan baserat på antalet artiklar som satts till 5 stycken.
        @articles = Article.paginate(page: params[:page], per_page: 5)
        # @articles = Article.all # Tidigare anrop till modellen.
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            # Skriver ut ett status meddelande.
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            # Kör metoden new.
            render 'new'
        end
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was sucessfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def show        
    end

    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted"
        redirect_to articles_path
    end

    private
        def set_article
            @article = Article.find(params[:id])
        end

        def article_params
            params.require(:article).permit(:title, :description, category_ids: [])
        end

        def require_same_user
            # Kollar om nuvarande user inte är skaparen av aktuell artikel eller inte admin.
            if current_user != @article.user and !current_user.admin?
                flash[:danger] = "You can only edit or delete your own articles"
                redirect_to root_path
            end
        end


end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <td><%= link_to article.title, article_path(article) %></td>
                </div><!-- /.article-title -->
                <div class="article-body">
                    <%= truncate(article.description, length: 100) %>
                    <div class="article-meta-details">
                        <small>Created by: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div><!-- /.article-meta-details -->
                </div><!-- /.article-body -->
                <% if article.categories.any? %>
                    <p>Categories: <%= render article.categories %></p>
                <% end %>
                <!-- Kollar om nuvarande user skapat aktuell artikel eller är admin, annars visas inte nedan angivna funktioner -->
                <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                    <div class="article-actions">
                        <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
                        <%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?" }, class: "btn btn-xs btn-danger" %>
                    </div><!-- /.article-actions -->
                <% end %>
            </div><!-- /.well -->
        </div>
    </div><!-- /.row -->
<% end %>

app/views/articles/_form.html.erb
<!-- Används för återanvändning (partials) i create och edit av en artikel -->

<!-- Visar felmeddelande -->
<%= render 'shared/errors', obj: @article %>

<!-- Formulär -->
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <!-- Title -->
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-8">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
            </div><!-- /.form-group -->

            <!-- Description -->
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-8">
                <%= f.text_area :description, class: "form-control", rows: 10, placeholder: "Body of article" %>
                </div>
            </div><!-- /.form-group -->

            <!-- Categories -->
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :Category %>
                </div>
                <div class="col-sm-8">
                    <!-- Visar alla tillgängliga kategorier som checkboxar -->
                    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox-inline") + cb.text} %>
                    <% end %>
                </div>
            </div><!-- /.form-group -->

            <!-- Button -->
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div><!-- /.form-group -->
        <% end %>

        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<!-- Hämtning/visning av formulär -->
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<div align="center">
    <%= will_paginate @articles %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
    <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<!-- Hämtning/visning av formulär -->
<%= render 'form' %>

app/views/articles/show.html.erb
<!-- Visar titel och textinnehåll för en artikel -->
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
    <!-- Om article har en user, annars skippar den koden fram tills description -->
    <% if @article.user %>
        <ul class="listing">
            <div class="row center">
                <div class="col-md-4 col-md-offset-4">
                    <li>Created by:</li>
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
                    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
                </div>
            </div>
        </ul>
    <% end %>

    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
    <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>
    <% end %>
    <div class="article-actions">
        <!-- Kollar om en user är inloggad och nuvarande user skapat aktuell artikel eller är admin, sen visas funktionalitet baserat om ett true eller false returneras -->
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
            <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
            <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?" }, class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
    </div><!-- /.article-actions -->
</div><!-- /.well -->