config/routes.rb
Rails.application.routes.draw do

  # Definierar rutter och root sätter start url.
  root 'pages#home'
  get 'about', to: 'pages#about'

  # Ny väg för att utföra crud på artiklar.
  resources :articles

  # Skapa users
  get 'signup', to: 'users#new'
  resources :users, expect: [:new]  
 
  # Inloggning på sidan
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Kategorier till artiklar, ska ej gå att ta bort.
  resources :categories, expect: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="http://users.du.se/~h15mavir/start.html">h15mavir</a> by Singh Development
        </small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<!-- Används för återanvändning (partials) -->

<!-- Visar meddelandet när artiklar lyckas skapas -->
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}" %>'>
                <a href"#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div><!-- /.alert -->
        <% end %>
    </div>
</div><!-- /.row -->

app/views/layouts/_navigation.html.erb
<!-- Bootstrap-styling för navigationsbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha-blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Sidlänkar -->
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        
        <!-- Kollar om en user är inloggad, sen visas dropdown-meny baserat om ett true eller false returneras -->
        <% if logged_in? %>
          <!-- Dropdown-meny Artiklar -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><%= link_to "Show Articles", articles_path %></li>
              <!-- Separerade länkar -->
              <li role="separator" class="divider"></li>
              <li><%= link_to "Home", root_path %></li>
            </ul>
          </li>
        <% end %>

        <!-- Dropdown-meny Kategorier -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Categories", categories_path %></li>
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <!-- Separerade länkar -->
              <% if logged_in? and current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create New Category", new_category_path %></li>
              <% end %>            
            </ul>
          </li>
      </ul>

      <!-- Högerjusterad menyval -->
      <ul class="nav navbar-nav navbar-right">
        <!-- Kollar om en user är inloggad, sen visas menyval baserat om ett true eller false returneras -->
        <% if logged_in? %>
          <li><%= link_to '<i class="glyphicon glyphicon-log-out"></i> Log out'.html_safe, logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toogle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= '<i class="glyphicon glyphicon-user"></i>'.html_safe if current_user.admin? %> Your Profile <%= 'Admin' if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit your profile', edit_user_path(current_user) %></li>
              <li><%= link_to 'View your profile', user_path(current_user) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '<i class="glyphicon glyphicon-log-in"></i> Log in'.html_safe, login_path %></li>
          <li><%= link_to '<i class="glyphicon glyphicon-edit"></i> Sign up'.html_safe, signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!-- Det som läggs till i body visas på samtliga sidor i views -->
  <body>
    <!-- Navigeringsbar, som visas på varje sida -->
    <%= render 'layouts/navigation' %>
    <!-- Hämtning/visning av flash-meddelanden -->
    <%= render 'layouts/messages' %>

    <!-- Lägger alla sidor i en kontainer -->
    <div class="container">
      <%= yield %>
    </div>
    <!-- Footer som visas på varje sida -->
    <%= render 'layouts/footer' %>

    <!-- Visar debugging i vyn -->
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>